package com.codecad.core.export

import com.codecad.core.ast.vec.Vec3
import com.codecad.core.brep.*
import com.codecad.core.brep.curve.Circle
import com.codecad.core.brep.curve.Curve
import com.codecad.core.brep.curve.Line
import com.codecad.core.brep.surface.CylindricalSurface
import com.codecad.core.brep.surface.PlaneSurface
import com.codecad.core.brep.surface.Surface
import com.codecad.core.part.Context
import com.codecad.core.volume.Volume
import java.nio.charset.StandardCharsets

class StepExport : ModelExport{
    private val Header =
        "ISO-10303-21;\n" +
        "HEADER;\n" +
        "/* Generated by software containing ST-Developer\n" +
        " * from STEP Tools, Inc. (www.steptools.com) \n" +
        " */\n" +
        "/* OPTION: using custom renumber hook */\n" +
        "\n" +
        "FILE_DESCRIPTION(\n" +
        "/* description */ ('STEP AP242',\n" +
        "'CAx-IF Rec.Pracs.---Representation and Presentation of Product Manufa\n" +
        "cturing Information (PMI)---4.0---2014-10-13',\n" +
        "'CAx-IF Rec.Pracs.---3D Tessellated Geometry---0.4---2014-09-14','2;1'),\n" +
        "\n" +
        "/* implementation_level */ '2;1');\n" +
        "\n" +
        "FILE_NAME(\n" +
        "/* name */ '64eddcb0e655f868ead72bdc',\n" +
        "/* time_stamp */ '2023-08-29T11:55:29Z',\n" +
        "/* author */ (''),\n" +
        "/* organization */ (''),\n" +
        "/* preprocessor_version */ 'ST-DEVELOPER v19.4',\n" +
        "/* originating_system */ '  ',\n" +
        "/* authorisation */ '  ');\n" +
        "\n" +
        "FILE_SCHEMA (('AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF { 1 0 10303 442 1 1 4 }'));\n" +
        "ENDSEC;\n\n" +
        "DATA;\n"

    private val Footer = "ENDSEC;\nEND-ISO-10303-21;"

    private val data = StringBuilder()
    private val vertices = hashMapOf<Vertex, Id>()
    private val edges = hashMapOf<Edge, Id>()
    private var index = 10

    data class Id(val value : Int)

    private fun tuple(vararg elem : Any) : String{
        return tuple(elem.asIterable())
    }

    private fun tuple(elems : Iterable<Any>) : String{
        val sb = StringBuilder()
        buildObject(sb, "", "", ",", "", elems)
        return sb.toString()
    }

    private fun serialize(vec3: Vec3) : String{
        return tuple(vec3.x, vec3.y, vec3.z)
    }

    private fun serialize(any: Any, sb : StringBuilder){
        when(any){
            is Boolean -> sb.append(if(any) ".T." else ".F.")
            is Double -> sb.append(any)
            is Int -> sb.append(any)
            is String -> sb.append(any)
            is Vec3 -> sb.append(serialize(any))
            is Id -> sb.append("#").append(any.value)
            else -> sb.append("?")
        }
    }

    private fun addNamedObject(struct: String, vararg args: Any, name : String = "") : Id{
        return addObject(struct, "'$name'", *args)
    }

    private fun addObject(struct: String, vararg args: Any) : Id{
        val currentIdx = index++

        data
            .append("#")
            .append(currentIdx)
            .append("=")

        buildObject(data, struct,"", ",", "", args.asIterable())
        data.append(";\n")
        return Id(currentIdx)
    }

    private fun addSpecialObject(vararg args: Any) : Id{
        val currentIdx = index++

        data
            .append("#")
            .append(currentIdx)
            .append("=")

        buildObject(data, "", "\n", "\n", "\n", args.asIterable())
        data.append(";\n")
        return Id(currentIdx)
    }

    private fun createObject(struct: String, vararg args: Any) : String{
        val sb = StringBuilder()
        buildObject(sb, struct, "", ",", "", args.asIterable())
        return sb.toString()
    }

    private fun buildObject(sb: StringBuilder, struct: String, prefix: String, delimiter: String, postfix: String, args: Iterable<Any>){
        sb
            .append(struct)
            .append("(")

        var sep = prefix
        for( arg in args ){
            sb.append(sep)
            serialize(arg, sb)
            sep = delimiter
        }

        sb.append(postfix).append(")")
    }

    private fun cartesianPoint(point : Vec3) : Id{
        return addNamedObject("CARTESIAN_POINT", serialize(point))
    }

    private fun direction(point : Vec3) : Id{
        return addNamedObject("DIRECTION", serialize(point))
    }

    private fun vector(point : Vec3) : Id{
        return addNamedObject("VECTOR", direction(point), 1.0)
    }

    private fun orientedEdge(edgeCurve: Id, orientation: Boolean) : Id{
        return addNamedObject("ORIENTED_EDGE", "*", "*", edgeCurve, orientation)
    }

    private fun circle(axisPlacement: Id, radius: Double) : Id{
        return addNamedObject("CIRCLE", axisPlacement, radius)
    }

    private fun line(point: Id, direction: Id) : Id{
        return addNamedObject("LINE", point, direction)
    }

    private fun edgeCurve(start: Id, end: Id, curve: Id, sense : Boolean) : Id{
        return addNamedObject("EDGE_CURVE", start, end, curve, sense)
    }

    private fun edgeCurve(edge: Edge) : Id{
        return edges.computeIfAbsent(edge){
            val bound = edge.bound

            val start = bound?.start?.let { vertexPoint(it) }
            val end = bound?.end?.let { vertexPoint(it) }

            val curve = buildCurve(edge.curve)
            val sense = (bound?.sense ?: Sense.CCW) != Sense.CW
            edgeCurve(start!!, end!!, curve, sense)
        }
    }

    private fun vertexPoint(vertex: Vertex) : Id{
        return vertices.computeIfAbsent(vertex){
            addNamedObject("VERTEX_POINT", cartesianPoint(vertex.point.eval()))
        }
    }

    private fun edgeLoop(orientedEdges: List<Id>) : Id{
        return addNamedObject("EDGE_LOOP", tuple(orientedEdges))
    }

    private fun faceBound(edgeLoop: Id, sense: Boolean) : Id{
        return addNamedObject("FACE_BOUND", edgeLoop, sense)
    }

    private fun advancedFace(faceBound: List<Id>, surface: Id, sense: Boolean) : Id{
        return addNamedObject("ADVANCED_FACE", tuple(faceBound), surface, sense)
    }

    private fun cylindricalSurface(axisPlacement: Id, radius: Double) : Id{
        return addNamedObject("CYLINDRICAL_SURFACE", axisPlacement, radius)
    }

    private fun plane(axisPlacement: Id) : Id{
        return addNamedObject("PLANE", axisPlacement)
    }

    private fun axisPlacement(point: Id, normal: Id, x : Id) : Id{
        return addNamedObject("AXIS2_PLACEMENT_3D", point, normal, x)
    }

    private fun closedShell(advancedFaces: List<Id>) : Id{
        return addNamedObject("CLOSED_SHELL", tuple(advancedFaces))
    }

    private fun openShell(advancedFaces: List<Id>) : Id{
        return addNamedObject("OPEN_SHELL", tuple(advancedFaces))
    }

    private fun shellSurface(shell: Id) : Id{
        return addNamedObject("SHELL_BASED_SURFACE_MODEL", tuple(shell), name= "Surface 1")
    }

    private fun solidBrep(shell: Id) : Id{
        return addNamedObject("MANIFOLD_SOLID_BREP", shell, name= "Part 1")
    }

    private fun geometricPresentationRepresentation(styledItems: List<Id>, context: Id) : Id{
        return addNamedObject("MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION", tuple(styledItems), context)
    }

    private fun presentationStyleAssignment() : Id{
        val color = addNamedObject("COLOUR_RGB", 0.615686274509804, 0.811764705882353, 0.929411764705882)
        val fillAreaStyleColor = addNamedObject("FILL_AREA_STYLE_COLOUR", color)
        val fillAreaStyle = addNamedObject("FILL_AREA_STYLE", tuple(fillAreaStyleColor))
        val surfaceStyleFillArea = addObject("SURFACE_STYLE_FILL_AREA", fillAreaStyle)
        val surfaceSideStyle = addNamedObject("SURFACE_SIDE_STYLE", tuple(surfaceStyleFillArea))
        val surfaceStyleUsage = addObject("SURFACE_STYLE_USAGE", ".BOTH.", surfaceSideStyle)
        return addObject("PRESENTATION_STYLE_ASSIGNMENT", tuple(surfaceStyleUsage))
    }

    private fun styledItem(solidBrep: Id, presentationStyleAssignment: Id) : Id{
        return addNamedObject("STYLED_ITEM", tuple(presentationStyleAssignment), solidBrep)
    }

    private fun applicationContext() : Id{
        val applicationContext = addNamedObject("APPLICATION_CONTEXT", name="managed model based 3d engineering")
        val applicationProtocolDefinition = addNamedObject("APPLICATION_PROTOCOL_DEFINITION",
            "'ap242_managed_model_based_3d_engineering'",
            2011,
            applicationContext,
            name="international standard")

        return applicationContext
    }

    private fun representationContext() : Id{
        val solidAngleUnit = addSpecialObject(
            createObject("NAMED_UNIT", "*"),
            createObject("SI_UNIT", "$", ".STERADIAN."),
            createObject("SOLID_ANGLE_UNIT"),
        )

        val radianUnit = addSpecialObject(
            createObject("NAMED_UNIT", "*"),
            createObject("PLANE_ANGLE_UNIT"),
            createObject("SI_UNIT", "$", ".RADIAN.")
        )

        val metreUnit = addSpecialObject(
            createObject("LENGTH_UNIT"),
            createObject("NAMED_UNIT", "*"),
            createObject("SI_UNIT", ".MILLI.", ".METRE.")
        )

        val uncertaintyMeasureWithUnit = addObject("UNCERTAINTY_MEASURE_WITH_UNIT",
            createObject("LENGTH_MEASURE", "5.E-6"),
            metreUnit,
            "'DISTANCE_ACCURACY_VALUE'",
            "'Maximum Tolerance applied to model'"
        )

        val representationContext = addSpecialObject(
            createObject("GEOMETRIC_REPRESENTATION_CONTEXT", 3),
            createObject("GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT", tuple(uncertaintyMeasureWithUnit)),
            createObject("GLOBAL_UNIT_ASSIGNED_CONTEXT", tuple(solidAngleUnit, radianUnit, metreUnit)),
            createObject("REPRESENTATION_CONTEXT", "'Part 1'", "'TOP_LEVEL_ASSEMBLY_PART'")
        )

        return representationContext
    }

    private fun shapeRepresentation(applicationContext: Id, representationContext: Id) : Id{
        val productContext = addNamedObject("PRODUCT_CONTEXT", applicationContext, "'mechanical'")
        val productCategory = addNamedObject("PRODUCT_CATEGORY", "''")
        val product = addNamedObject("PRODUCT", "'Part 1'", "'Part 1'", tuple(productContext), name="Part 1")

        val productRelatedProductCategory = addNamedObject("PRODUCT_RELATED_PRODUCT_CATEGORY", "''", tuple(product))
        val productDefFormWithSpecSource = addNamedObject("PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE", "''", product, ".NOT_KNOWN.")
        val productDefinitionContext = addNamedObject("PRODUCT_DEFINITION_CONTEXT", applicationContext, "'design'")

        val productDefinition = addNamedObject("PRODUCT_DEFINITION", "''", productDefFormWithSpecSource, productDefinitionContext)
        val productDefinitionShape = addNamedObject("PRODUCT_DEFINITION_SHAPE", "''", productDefinition)

        val normal = direction(Vec3(0.0, 0.0, 1.0))
        val xAxis = direction(Vec3(1.0, 0.0, 0.0))
        val point = cartesianPoint(Vec3.ZERO)
        val axisPlacement = axisPlacement(point, normal, xAxis)

        val shapeRepresentation = addNamedObject("SHAPE_REPRESENTATION", tuple(axisPlacement), representationContext, name = "Part 1")
        val shapeDefinitionRepresentation = addObject("SHAPE_DEFINITION_REPRESENTATION", productDefinitionShape, shapeRepresentation)
        return shapeRepresentation
    }

    private fun buildAxisPlacement(workplane: Workplane) : Id{
        return axisPlacement(cartesianPoint(workplane.origin), direction(workplane.normal), direction(workplane.axisX))
    }

    private fun buildSurface(surface: Surface) : Id{
        val axisPlacement = buildAxisPlacement(surface.workplane.eval())
        return when(surface){
            is CylindricalSurface ->
                cylindricalSurface(axisPlacement, surface.radius.evalDouble() )
            is PlaneSurface -> plane(axisPlacement)
            else -> throw RuntimeException("Unknown surface")
        }
    }

    private fun buildCurve(curve: Curve) : Id{
        return when(curve){
            is Circle -> circle(buildAxisPlacement(curve.workplane.eval()), curve.radius.evalDouble())
            is Line -> line(cartesianPoint(curve.point.eval()), vector(curve.direction.eval()))
            else -> throw RuntimeException("Unknown surface")
        }
    }

    private fun buildAdvancedFace(face : Face) : Id{
        val surface = buildSurface(face.surface)

        val stepBounds = arrayListOf<Id>()
        for(faceBound in face.bounds){
            val stepOrientedEdges = arrayListOf<Id>()
            for(edgeLoop in faceBound.edgeLoop){
                val orientedEdge = edgeLoop.edge
                val edge = orientedEdge.edge

                val stepEdgeCurve = edgeCurve(edge)

                val stepOrientedEdge =
                    orientedEdge(stepEdgeCurve,
                    orientedEdge.orientation == EdgeOrientation.Forward)

                stepOrientedEdges.add(stepOrientedEdge)
            }

            val stepSense = faceBound.sense == FaceBoundSense.Inside
            val stepEdgeLoop = edgeLoop(stepOrientedEdges)
            val stepFaceBound = faceBound(stepEdgeLoop, stepSense)
            stepBounds.add(stepFaceBound)
        }

        return advancedFace(stepBounds, surface, true)
    }

    private fun buildShell(shell: Shell) : Id{
        val stepAdvancedFaces = arrayListOf<Id>()
        for(face in shell.faces){
            val advancedFace = buildAdvancedFace(face)
            stepAdvancedFaces.add(advancedFace)
        }

        return closedShell(stepAdvancedFaces)
    }

    private fun buildVolume(volume: Volume) : Id{
        val shell = buildShell(volume.shells.first())
        return solidBrep(shell)
    }

    private fun buildFace(face: Face) : Id{
        val openShell = openShell(listOf(buildAdvancedFace(face)))
        val surfaceModel = shellSurface(openShell)
        return surfaceModel
    }

    override fun export(context: Context): ByteArray{
        data.append(Header)
        val models = arrayListOf<Id>()
        val breps = arrayListOf<Id>()
        val surfaceModels = arrayListOf<Id>()
        for( face in context.faces ){
            val face = buildFace(face)
            models.add(face)
            surfaceModels.add(face)
        }

        for( volume in context.volumes ){
            val brep = buildVolume(volume)
            models.add(brep)
            breps.add(brep)
        }

        val styledItems = arrayListOf<Id>()
        val style = presentationStyleAssignment()
        val applicationContext = applicationContext()
        val representationContext = representationContext()
        val shapeRepresentation = shapeRepresentation(applicationContext, representationContext)

        for(model in models){
            styledItems.add(styledItem(model, style))
        }

        val shapeReps = arrayListOf<Id>()
        for(brep in breps){
            shapeReps.add(addNamedObject("ADVANCED_BREP_SHAPE_REPRESENTATION", tuple(brep), representationContext))
        }

        for(surface in surfaceModels){
            shapeReps.add(addNamedObject("MANIFOLD_SURFACE_SHAPE_REPRESENTATION", tuple(surface), representationContext))
        }

        shapeReps.forEach {
            addNamedObject("SHAPE_REPRESENTATION_RELATIONSHIP", "''", shapeRepresentation, it)
        }

        geometricPresentationRepresentation(styledItems, representationContext)
        data.append(Footer)
        return data.toString().toByteArray(StandardCharsets.UTF_8)
    }

}
