package com.codecad.core.export

import com.codecad.core.ast.vec.Vec3
import com.codecad.core.brep.*
import com.codecad.core.brep.curve.Circle
import com.codecad.core.brep.curve.Curve
import com.codecad.core.brep.curve.Line
import com.codecad.core.brep.surface.CylindricalSurface
import com.codecad.core.brep.surface.PlaneSurface
import com.codecad.core.brep.surface.Surface
import com.codecad.core.part.Context
import com.codecad.core.volume.Volume
import java.nio.charset.StandardCharsets

class StepExport : ModelExport{
    private val Header =
        "ISO-10303-21;\n" +
        "HEADER;\n" +
        "/* Generated by software containing ST-Developer\n" +
        " * from STEP Tools, Inc. (www.steptools.com) \n" +
        " */\n" +
        "/* OPTION: using custom renumber hook */\n" +
        "\n" +
        "FILE_DESCRIPTION(\n" +
        "/* description */ ('STEP AP242',\n" +
        "'CAx-IF Rec.Pracs.---Representation and Presentation of Product Manufa\n" +
        "cturing Information (PMI)---4.0---2014-10-13',\n" +
        "'CAx-IF Rec.Pracs.---3D Tessellated Geometry---0.4---2014-09-14','2;1'),\n" +
        "\n" +
        "/* implementation_level */ '2;1');\n" +
        "\n" +
        "FILE_NAME(\n" +
        "/* name */ '64eddcb0e655f868ead72bdc',\n" +
        "/* time_stamp */ '2023-08-29T11:55:29Z',\n" +
        "/* author */ (''),\n" +
        "/* organization */ (''),\n" +
        "/* preprocessor_version */ 'ST-DEVELOPER v19.4',\n" +
        "/* originating_system */ '  ',\n" +
        "/* authorisation */ '  ');\n" +
        "\n" +
        "FILE_SCHEMA (('AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF { 1 0 10303 442 1 1 4 }'));\n" +
        "ENDSEC;\n\n" +
        "DATA;\n"

    private val Footer = "ENDSEC;\nEND-ISO-10303-21;"

    private val data = StringBuilder()
    private val vertices = hashMapOf<Vertex, Id>()
    private val edges = hashMapOf<Edge, Id>()
    private var index = 10

    data class Id(val value : Int)

    private fun tuple(vararg elem : Any) : String{
        return tuple(elem.asIterable())
    }

    private fun tuple(elems : Iterable<Any>) : String{
        val sb = StringBuilder()
        buildObject(sb, "", "", ",", "", elems)
        return sb.toString()
    }

    private fun serialize(vec3: Vec3) : String{
        return tuple(vec3.x, vec3.y, vec3.z)
    }

    private fun serialize(any: Any, sb : StringBuilder){
        when(any){
            is Boolean -> sb.append(if(any) ".T." else ".F.")
            is Double -> sb.append(any)
            is Int -> sb.append(any)
            is String -> sb.append(any)
            is Vec3 -> sb.append(serialize(any))
            is Id -> sb.append("#").append(any.value)
            else -> sb.append("?")
        }
    }

    private fun addNamedObject(struct: String, vararg args: Any, name : String = "") : Id{
        return addObject(struct, "'$name'", *args)
    }

    private fun addObject(struct: String, vararg args: Any) : Id{
        val currentIdx = index++

        data
            .append("#")
            .append(currentIdx)
            .append("=")

        buildObject(data, struct,"", ",", "", args.asIterable())
        data.append(";\n")
        return Id(currentIdx)
    }

    private fun addSpecialObject(vararg args: Any) : Id{
        val currentIdx = index++

        data
            .append("#")
            .append(currentIdx)
            .append("=")

        buildObject(data, "", "\n", "\n", "\n", args.asIterable())
        data.append(";\n")
        return Id(currentIdx)
    }

    private fun createObject(struct: String, vararg args: Any) : String{
        val sb = StringBuilder()
        buildObject(sb, struct, "", ",", "", args.asIterable())
        return sb.toString()
    }

    private fun buildObject(sb: StringBuilder, struct: String, prefix: String, delimiter: String, postfix: String, args: Iterable<Any>){
        sb
            .append(struct)
            .append("(")

        var sep = prefix
        for( arg in args ){
            sb.append(sep)
            serialize(arg, sb)
            sep = delimiter
        }

        sb.append(postfix).append(")")
    }

    private fun createCartesianPoint(point : Vec3) : Id{
        return addNamedObject("CARTESIAN_POINT", serialize(point))
    }

    private fun createDirection(point : Vec3) : Id{
        return addNamedObject("DIRECTION", serialize(point))
    }

    private fun createVector(point : Vec3) : Id{
        return addNamedObject("VECTOR", createDirection(point), 1.0)
    }

    private fun createOrientedEdge(edgeCurve: Id, orientation: Boolean) : Id{
        return addNamedObject("ORIENTED_EDGE", "*", "*", edgeCurve, orientation)
    }

    private fun createCircle(axisPlacement: Id, radius: Double) : Id{
        return addNamedObject("CIRCLE", axisPlacement, radius)
    }

    private fun createLine(point: Id, direction: Id) : Id{
        return addNamedObject("LINE", point, direction)
    }

    private fun createEdgeCurve(start: Id, end: Id, curve: Id, sense : Boolean) : Id{
        return addNamedObject("EDGE_CURVE", start, end, curve, sense)
    }

    private fun createEdgeCurve(edge: Edge) : Id{
        return edges.computeIfAbsent(edge){
            val bound = edge.bound

            val start = bound?.start?.let { createVertexPoint(it) }
            val end = bound?.end?.let { createVertexPoint(it) }

            val curve = createCurve(edge.curve)
            val sense = (bound?.sense ?: Sense.CCW) != Sense.CW
            createEdgeCurve(start!!, end!!, curve, sense)
        }
    }

    private fun createVertexPoint(vertex: Vertex) : Id{
        return vertices.computeIfAbsent(vertex){
            addNamedObject("VERTEX_POINT", createCartesianPoint(vertex.point.eval()))
        }
    }

    private fun createEdgeLoop(orientedEdges: List<Id>) : Id{
        return addNamedObject("EDGE_LOOP", tuple(orientedEdges))
    }

    private fun createFaceBound(edgeLoop: Id, sense: Boolean) : Id{
        return addNamedObject("FACE_BOUND", edgeLoop, sense)
    }

    private fun createAdvancedFace(faceBound: List<Id>, surface: Id, sense: Boolean) : Id{
        return addNamedObject("ADVANCED_FACE", tuple(faceBound), surface, sense)
    }

    private fun createCylindricalSurface(axisPlacement: Id, radius: Double) : Id{
        return addNamedObject("CYLINDRICAL_SURFACE", axisPlacement, radius)
    }

    private fun createPlane(axisPlacement: Id) : Id{
        return addNamedObject("PLANE", axisPlacement)
    }

    private fun createAxisPlacement(point: Id, normal: Id, x : Id) : Id{
        return addNamedObject("AXIS2_PLACEMENT_3D", point, normal, x)
    }

    private fun closedShell(advancedFaces: List<Id>) : Id{
        return addNamedObject("CLOSED_SHELL", tuple(advancedFaces))
    }

    private fun createOpenShell(advancedFaces: List<Id>) : Id{
        return addNamedObject("OPEN_SHELL", tuple(advancedFaces))
    }

    private fun createShellSurface(shell: Id) : Id{
        return addNamedObject("SHELL_BASED_SURFACE_MODEL", tuple(shell), name= "Surface 1")
    }

    private fun createSolidBrep(shell: Id) : Id{
        return addNamedObject("MANIFOLD_SOLID_BREP", shell, name= "Part 1")
    }

    private fun createGeometricPresentationRepresentation(styledItems: List<Id>, context: Id) : Id{
        return addNamedObject("MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION", tuple(styledItems), context)
    }

    private fun createPresentationStyleAssignment() : Id{
        val color = addNamedObject("COLOUR_RGB", 0.615686274509804, 0.811764705882353, 0.929411764705882)
        val fillAreaStyleColor = addNamedObject("FILL_AREA_STYLE_COLOUR", color)
        val fillAreaStyle = addNamedObject("FILL_AREA_STYLE", tuple(fillAreaStyleColor))
        val surfaceStyleFillArea = addObject("SURFACE_STYLE_FILL_AREA", fillAreaStyle)
        val surfaceSideStyle = addNamedObject("SURFACE_SIDE_STYLE", tuple(surfaceStyleFillArea))
        val surfaceStyleUsage = addObject("SURFACE_STYLE_USAGE", ".BOTH.", surfaceSideStyle)
        return addObject("PRESENTATION_STYLE_ASSIGNMENT", tuple(surfaceStyleUsage))
    }

    private fun createStyledItem(solidBrep: Id, presentationStyleAssignment: Id) : Id{
        return addNamedObject("STYLED_ITEM", tuple(presentationStyleAssignment), solidBrep)
    }

    private fun createApplicationContext() : Id{
        val applicationContext = addNamedObject("APPLICATION_CONTEXT", name="managed model based 3d engineering")
        val applicationProtocolDefinition = addNamedObject("APPLICATION_PROTOCOL_DEFINITION",
            "'ap242_managed_model_based_3d_engineering'",
            2011,
            applicationContext,
            name="international standard")

        return applicationContext
    }

    private fun createRepresentationContext() : Id{
        val solidAngleUnit = addSpecialObject(
            createObject("NAMED_UNIT", "*"),
            createObject("SI_UNIT", "$", ".STERADIAN."),
            createObject("SOLID_ANGLE_UNIT"),
        )

        val radianUnit = addSpecialObject(
            createObject("NAMED_UNIT", "*"),
            createObject("PLANE_ANGLE_UNIT"),
            createObject("SI_UNIT", "$", ".RADIAN.")
        )

        val metreUnit = addSpecialObject(
            createObject("LENGTH_UNIT"),
            createObject("NAMED_UNIT", "*"),
            createObject("SI_UNIT", ".MILLI.", ".METRE.")
        )

        val uncertaintyMeasureWithUnit = addObject("UNCERTAINTY_MEASURE_WITH_UNIT",
            createObject("LENGTH_MEASURE", "5.E-6"),
            metreUnit,
            "'DISTANCE_ACCURACY_VALUE'",
            "'Maximum Tolerance applied to model'"
        )

        val representationContext = addSpecialObject(
            createObject("GEOMETRIC_REPRESENTATION_CONTEXT", 3),
            createObject("GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT", tuple(uncertaintyMeasureWithUnit)),
            createObject("GLOBAL_UNIT_ASSIGNED_CONTEXT", tuple(solidAngleUnit, radianUnit, metreUnit)),
            createObject("REPRESENTATION_CONTEXT", "'Part 1'", "'TOP_LEVEL_ASSEMBLY_PART'")
        )

        return representationContext
    }

    private fun createShapeRepresentation(applicationContext: Id, representationContext: Id) : Id{
        val productContext = addNamedObject("PRODUCT_CONTEXT", applicationContext, "'mechanical'")
        val productCategory = addNamedObject("PRODUCT_CATEGORY", "''")
        val product = addNamedObject("PRODUCT", "'Part 1'", "'Part 1'", tuple(productContext), name="Part 1")

        val productRelatedProductCategory = addNamedObject("PRODUCT_RELATED_PRODUCT_CATEGORY", "''", tuple(product))
        val productDefFormWithSpecSource = addNamedObject("PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE", "''", product, ".NOT_KNOWN.")
        val productDefinitionContext = addNamedObject("PRODUCT_DEFINITION_CONTEXT", applicationContext, "'design'")

        val productDefinition = addNamedObject("PRODUCT_DEFINITION", "''", productDefFormWithSpecSource, productDefinitionContext)
        val productDefinitionShape = addNamedObject("PRODUCT_DEFINITION_SHAPE", "''", productDefinition)

        val normal = createDirection(Vec3(0.0, 0.0, 1.0))
        val xAxis = createDirection(Vec3(1.0, 0.0, 0.0))
        val point = createCartesianPoint(Vec3.ZERO)
        val axisPlacement = createAxisPlacement(point, normal, xAxis)

        val shapeRepresentation = addNamedObject("SHAPE_REPRESENTATION", tuple(axisPlacement), representationContext, name = "Part 1")
        val shapeDefinitionRepresentation = addObject("SHAPE_DEFINITION_REPRESENTATION", productDefinitionShape, shapeRepresentation)
        return shapeRepresentation
    }

    private fun createAxisPlacement(workplane: Workplane) : Id{
        return createAxisPlacement(createCartesianPoint(workplane.origin), createDirection(workplane.normal), createDirection(workplane.axisX))
    }

    private fun createSurface(surface: Surface) : Id{
        val axisPlacement = createAxisPlacement(surface.workplane.eval())
        return when(surface){
            is CylindricalSurface ->
                createCylindricalSurface(axisPlacement, surface.radius.evalDouble() )
            is PlaneSurface -> createPlane(axisPlacement)
            else -> throw RuntimeException("Unknown surface")
        }
    }

    private fun createCurve(curve: Curve) : Id{
        return when(curve){
            is Circle -> createCircle(createAxisPlacement(curve.workplane.eval()), curve.radius.evalDouble())
            is Line -> createLine(createCartesianPoint(curve.point.eval()), createVector(curve.direction.eval()))
            else -> throw RuntimeException("Unknown surface")
        }
    }

    private fun createAdvancedFace(face : Face) : Id{
        val surface = createSurface(face.surface)

        val stepBounds = arrayListOf<Id>()
        for(faceBound in face.bounds){
            val stepOrientedEdges = arrayListOf<Id>()
            for(edgeLoop in faceBound.edgeLoop){
                val orientedEdge = edgeLoop.edge
                val edge = orientedEdge.edge

                val stepEdgeCurve = createEdgeCurve(edge)

                val stepOrientedEdge =
                    createOrientedEdge(stepEdgeCurve,
                    orientedEdge.orientation == EdgeOrientation.Forward)

                stepOrientedEdges.add(stepOrientedEdge)
            }

            val stepSense = faceBound.sense == FaceBoundSense.Inside
            val stepEdgeLoop = createEdgeLoop(stepOrientedEdges)
            val stepFaceBound = createFaceBound(stepEdgeLoop, stepSense)
            stepBounds.add(stepFaceBound)
        }

        return createAdvancedFace(stepBounds, surface, true)
    }

    private fun createShell(shell: Shell) : Id{
        val stepAdvancedFaces = arrayListOf<Id>()
        for(face in shell.faces){
            val advancedFace = createAdvancedFace(face)
            stepAdvancedFaces.add(advancedFace)
        }

        return closedShell(stepAdvancedFaces)
    }

    private fun createVolume(volume: Volume) : Id{
        val shell = createShell(volume.shells.first())
        return createSolidBrep(shell)
    }

    private fun createFace(face: Face) : Id{
        val openShell = createOpenShell(listOf(createAdvancedFace(face)))
        val surfaceModel = createShellSurface(openShell)
        return surfaceModel
    }

    private fun createShapeRepresentationRelationship(shapeRepresentation: Id, shapeRep: Id){
        addNamedObject("SHAPE_REPRESENTATION_RELATIONSHIP", "''", shapeRepresentation, shapeRep)
    }

    override fun export(context: Context): ByteArray{
        data.append(Header)

        val style = createPresentationStyleAssignment()
        val applicationContext = createApplicationContext()
        val representationContext = createRepresentationContext()
        val shapeRepresentation = createShapeRepresentation(applicationContext, representationContext)

        val styledItems = arrayListOf<Id>()
        for( face in context.faces ){
            val item = createFace(face)
            styledItems.add(createStyledItem(item, style))
            val shapeRep = addNamedObject("MANIFOLD_SURFACE_SHAPE_REPRESENTATION", tuple(item), representationContext)
            createShapeRepresentationRelationship(shapeRepresentation, shapeRep)
        }

        for( volume in context.volumes ){
            val item = createVolume(volume)
            styledItems.add(createStyledItem(item, style))
            val shapeRep = addNamedObject("ADVANCED_BREP_SHAPE_REPRESENTATION", tuple(item), representationContext)
            createShapeRepresentationRelationship(shapeRepresentation, shapeRep)
        }

        createGeometricPresentationRepresentation(styledItems, representationContext)
        data.append(Footer)
        return data.toString().toByteArray(StandardCharsets.UTF_8)
    }

}
